### ISSUE TITLE
Notifications for incoming invoice payment and keysend - Windows

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-kotlin-ui#101]
**Task**

Add push notification on windows for keysends and incoming invoices.

Files involved:

`SphinxRepository.kt`

On `fun onSocketIOMessageReceived` implement `SphinxSocketIOMessage.Type.InvoicePayment` and `SphinxSocketIOMessage.Type.MessageType.KeySend` and send notification using `sphinxNotificationManager.notify` as on `fun showNotification` with the following format:

### Invoice Payment
**Title:**
_Invoice Payment Received_
**Text:** 
_Amount: 1 sats
Memo: Test Memo_

### Keysend
**Title:** 
_Keysend Received_
**Text:** 
_Amount: 1 sats_

**Comment by gouravmpk** [comment]
is this closed ? @tomsmith8

**Comment by tomsmith8** [comment]
Nope, I can assign!

**Comment by ecurrencyhodler** [comment]
Closed by #248
