### ISSUE TITLE
Transactions list improvements

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-kotlin-ui#104]
Apply new designs to transactions list rows based on Mac designs and start including failed payments on list

Files involved:
```
- TransactionsUI.kt
- TransactionsViewModel.kt
```

## Incoming payment UI
<img width="450" alt="Screenshot 2023-11-28 at 10 20 06" src="https://github.com/stakwork/sphinx-kotlin-ui/assets/2242281/c2cff468-7478-4d16-9e4d-9b89fa07b0c9">

- background color: #1E2934
- Name text color: #909BAA
- Amount text color: #FFFFFF
- Sat text color: #556171
- Date text color: #556171

Icon image:

![received-icon@3x](https://github.com/stakwork/sphinx-kotlin-ui/assets/2242281/f6a09665-bf41-4f60-b6c6-683909814870)

## Outgoing payment UI
<img width="450" alt="Screenshot 2023-11-28 at 10 20 11" src="https://github.com/stakwork/sphinx-kotlin-ui/assets/2242281/738800f0-078b-43cc-9f77-f0a6705f35e9">

- background color: #1A232D
- Name text color: #909BAA
- Amount text color: #FFFFFF
- Sat text color: #556171
- Date text color: #556171

Icon image:

![sent-icon@3x](https://github.com/stakwork/sphinx-kotlin-ui/assets/2242281/175f8a88-0568-4057-8fe5-112abfee1141)

## Failed payment UI

To start getting failed payments a new url param (`include_failures=true`) needs to be added to the `fun getPayments` endpoint on `NetworkQueryMessageImpl.kt`

If the object coming on transactions list contains an `error_message` not empty, then it's a failed payment and it should show like this: 

<img width="451" alt="Screenshot 2023-11-28 at 10 27 53" src="https://github.com/stakwork/sphinx-kotlin-ui/assets/2242281/ade1e6df-07b3-4269-90af-8d5f914d88ca">

- icon and red label color: #ED7474

Icon image: 

![warning-icon@3x](https://github.com/stakwork/sphinx-kotlin-ui/assets/2242281/5ef6cfd0-a2b6-4a6a-84ac-fe712c268906)

When clicking on failed payment row it should expand and show failure reason contained in `error_message` field of the transaction object returned from relay:

<img width="451" alt="Screenshot 2023-11-28 at 10 27 59" src="https://github.com/stakwork/sphinx-kotlin-ui/assets/2242281/b90b9700-fb14-437d-996b-95e48245c770">

**Comment by okhot** [comment]
I can help with this ticket!

**Comment by i-am-yuvi** [comment]
Hey @tomastiminskas, I was trying to run the app locally but I got the error:

```No matching configuration of project :sphinx-kotlin-core was found```

Can you help me resolve this?

**Comment by tomastiminskas** [comment]
Hey @i-am-yuvi I never experienced that issue and hard to know what is the problem without more details. The `sphinx-kotlin-core` is a submodule of `sphinx-kotlin-ui` so first of all double check if you cloned the submodules.

I can also suggest to use _IntelliJ Idea_ instead of _Android Studio_. I remember trying to run the project on AS initially and having several issues. In my case I'm using _IntelliJ IDEA 2023.2.5 (Community Edition)_

**Comment by turizspace** [comment]
Hi there ! Running this on desktop to make the transactions list improvement.
