### ISSUE TITLE
Solution for cloning submodule issue 

### ISSUE THREAD

**Issue by MathRoda** [stakwork/sphinx-kotlin-ui#81]
### Issue
this only happens when you clone the `sphinx-kotlin-ui` repository through `HTTPS` rather than `SSH`
because in `.gitmodule` file the url equals `git@github.com:stakwork/sphinx-kotlin-core.git` which makes it ask for SSH public keys

### Solution

- in cloned project directory open `.gitmodule` file
- swap url value from `git@github.com:stakwork/sphinx-kotlin-core.git` to `https://github.com/stakwork/sphinx-kotlin-core.git`
- in terminal run `git submodule sync` and then run `git submodule update --init`
- now build up gradle and it should work fine

![image](https://user-images.githubusercontent.com/92212925/203771324-304ea0da-80c9-4bcb-b7c3-150e377ff119.png)

**Comment by tomastiminskas** [comment]
Fix pushed to master
