### ISSUE TITLE
View transaction history on desktop

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-kotlin-ui#99]
**Task**

Loom: [here](https://www.loom.com/share/1949c8fe333c441c904d68d12d9f7a55?sid=b92d37bf-9545-4476-9914-2d30f011a310)

We need to support viewing transaction history for desktop users.

![Image](https://github.com/stakwork/sphinx-kotlin-ui/assets/142233216/0997eda0-1f80-41d1-ba0c-37867dc8f6a8)

**Design**

- Add Send, Transactions & Receive to the bottom of the contacts list

<img width="371" alt="image" src="https://github.com/stakwork/sphinx-kotlin-ui/assets/142233216/52fd0650-0ce2-4a28-8096-d1178b66e444">

Mac Repo where it is currently implemented: https://github.com/stakwork/sphinx-mac

**Acceptance Criteria**

- [ ] Desktop App works the same as Mac (as per Loom)
- [ ] Share video recording of transactions, send and receive functionality

**Comment by tomastiminskas** [comment]
@tomsmith8 I think we can implement it in the same way we did on Mac. But I thought you were going to create a bounty for this. Let me know, otherwise I can work on it this week
